# Generated by Django 6.1.1 on 2026-09-15 16:10

import django.db.models.deletion
import experiencias.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('descripcion', models.TextField(verbose_name='Descripcion')),
            ],
        ),
        migrations.CreateModel(
            name='Experiencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('descripcion', models.TextField(verbose_name='Descripcion')),
                ('imagen', models.ImageField(upload_to=experiencias.models.renombrar_imagen, verbose_name='Imagen')),
                ('precio', models.FloatField(verbose_name='Precio')),
                ('duracion', models.IntegerField(verbose_name='Duracion')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='experiencias.categoria', verbose_name='Categoria')),
            ],
        ),
    ]
